config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Nutstore.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

Nutstore/models.py
from django.db import models
#from accounts.models import CustomUser


#City table
class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

#Warehouse table
class Warehouse(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    location = models.CharField(max_length = 500)

    def __str__(self):
        return self.name

#Products table
class Product(models.Model):
    CATEGORY_CHOICES = (
        ('pistachio', 'Pistachio'),
        ('almond', 'Almond'),
        ('cashew', 'Cashew'),
        ('peanuts', 'Peanuts'),
        ('confectioneries', 'Confectioneries'),
        ('dried fruits', 'Dried Fruits'),
        ('snacks', 'Snacks'),
        ('other', 'Other Products'),
    )
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    stock = models.DecimalField(max_digits = 10, decimal_places = 3) 
    category = models.CharField(max_length=200, choices=CATEGORY_CHOICES)
    image = models.URLField(blank=True)
    #image = models.ImageField(upload_to='product_images/', blank=True, null=True)

    def __str__(self):
        return self.name



#THE MODEL FOR SHOPPING CART:
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    weight = models.DecimalField(max_digits=9, decimal_places=3)    #this actually allows us to have a weight up to 999999.99
    is_active = models.BooleanField(default=True)


#new order model:
class Order(models.Model):
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    STATUS_CHOICES = (
        ('preparing', 'Preparing'),
        ('delivered', 'Delivered'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='preparing') 

    def __str__(self):
        return f"Order #{self.id} by {self.user.username}"
    

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
  <div class="row align-items-center">
    <div class="col-lg-6">
      <h1 class="mb-4">About Our Nut Store</h1>
      <p class="lead">Welcome to our nut store! We are a family-owned business that has been providing high-quality nuts to our customers for over 50 years.</p>
      <p>Our story began in the early 1970s when our founder, Melina Mehrani (The Ghost), decided to turn her passion for nuts into a business. She started by selling her homemade nut mixes at local farmers' markets, and soon her products became popular among the community. With the support of her family and customers, Melina opened her first store in downtown in 1975.</p>
      <p>Over the years, our store has grown and evolved, but one thing has remained constant: our commitment to providing the freshest and highest quality nuts to our customers. We source our nuts from trusted suppliers and roast them in-house to ensure that they are packed with flavor and nutrition.</p>
      <p>In the 1990s, we expanded our product line to include a variety of nut butters and snacks, such as trail mixes and granolas. We also started offering gift baskets and custom nut mixes for special occasions, such as weddings and corporate events.</p>
      <p>Today, our store is run by Melina's real body (Not the Ghost), Melina, who shares her ghost's passion for nuts and continues to uphold our tradition of excellence. We are proud to be a part of the local community and to have served generations of customers.</p>
      <p>Thank you for choosing our store for your nut needs. We hope you enjoy our products as much as we enjoy making them!</p>
    </div>
    <div class="col-lg-6">
      <img src="{% static 'images/store.jpg' %}" class="img-fluid rounded" alt="Your Image">
    </div>
  </div>
</div>
{% endblock %}

templates/add_to_cart.html
{% extends 'base.html' %}

{% block content %}
  <div class="row justify-content-center" style="margin: 1.5rem;">
    <div class="col-md-6">
      <div class="card border-0 shadow-sm">
        {% if product.image %}
          <img src="{{ product.image }}" class="card-img-top" alt="{{ product.name }}">
        {% endif %}
        <div class="card-body">
          <h1 class="card-title">{{ product.name }}</h1>
          <p class="card-text">{{ product.description }}</p>
          <p class="card-text font-weight-bold">Price: {{ product.price }} $</p>
          {% if request.user.is_authenticated %}
            {% if request.user.is_seller %}
              <form method="post" action="{% url 'add_to_cart' product.id %}">
                {% csrf_token %}
                <div class="form-group">
                  <label for="weight">Weight (kg):</label>
                  <input type="number" class="form-control" name="weight" value="0" min="0" step="5" max="999999.999">
                </div>
                <button type="submit" class="btn btn-primary btn-block">Add to Cart</button>
              </form>
            {% else %}
              <form method="post" action="{% url 'add_to_cart' product.id %}">
                {% csrf_token %}
                <div class="form-group">
                  <label for="weight">Weight (g):</label>
                  <input type="number" class="form-control" name="weight" value="0" min="0" step="50" max="999999.999">
                </div>
                <button type="submit" class="btn btn-primary btn-block">Add to Cart</button>
              </form>
            {% endif %}
          {% else %}
            <p><a href="{% url 'login' %}?next={{ request.path }}">Log in</a> to purchase this product.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>


  <style>
    .card {
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .card-img-top {
      border-top-left-radius: 10px;
      border-top-right-radius: 10px;
      height: 250px;
      object-fit: cover;
    }

    .form-control {
      border-radius: 20px;
    }

    .btn-primary {
      border-radius: 20px;
      padding: 10px 20px;
      color: white;
      background-color: #7aa66f;
      border-color: #7aa66f;
    }

    .btn-primary:hover {
      background-color: #586e52;
      border-color: #586e52;
    }

    
    body {
      /* fallback for old browsers */
        background: #F2F0EB;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, #F2F0EB, rgb(167, 175, 151));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, #F2F0EB, rgb(167, 175, 151))
    }
  </style>
{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html> 
<html class="vh-100">
<head>
	<title>The Nut Store</title>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<!-- Icons -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-y9m8Ua8wX5R7VxZaT4QWlZJjLl+9s6HxVZzCm6cY7vJ/iR9q6b9sre6lYy9XlWc8" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
	<!-- Font Awesome icons -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body class="vh-100">
	
	<!--Upper Header-->
	<div class="header" style="background-color: black;">
		<div class="container-fluid">
			<div class="row align-items-center">
				<div class="col-md-6">
					<a class="navbar-brand" href="{% url 'home' %}" style="width: 10%; height: 10%;">
						<img src="{% static 'images/logo2.png' %}" class="d-inline-block align-top" alt="Logo" >
					</a>
					<a class="navbar-brand" href="{% url 'home' %}" style="color: white;"><h3>The Nut Store</h3></a>
				</div>
				<div class="col-md-6 text-right">
					{% if user.is_authenticated %}
					<a href="{% url 'logout' %}" class="btn btn-danger"><i class="fa fa-sign-out-alt"></i> Log out</a>
					{% else %}
					<a href="{% url 'login' %}" class="btn btn-primary"><i class="fa fa-sign-in-alt"></i> Log in</a>
					<a href="{% url 'signup' %}" class="btn btn-secondary"><i class="fa fa-user-plus" ></i> Sign up</a>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	<!-- Lower header -->
	<div class="lower-header" style="background-color:#4b4b4b;">
		<div class="container-fluid">
			<div class="row align-items-center">
				<div class="col-md-6">
					<ul class="nav">
						<li class="nav-item">
							<a class="nav-link active" href="{% url 'home' %}"><strong>Home</strong></a>
						</li>
						<li class="nav-item dropdown">
							<a
							  class="nav-link dropdown-toggle"
							  href="#"
							  id="navbarDropdown"
							  role="button"
							  data-bs-toggle="dropdown"
							  aria-expanded="false"
							>
							  Categories
							</a>
							<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							  {% for category in categories %}
							  <li><a class="dropdown-item" href="{% url 'category' category %}">{{ category|title }}</a></li>
							  {% endfor %}
							</ul>
						</li>
						
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'profile' %}">Profile</a>
						</li>
						{% endif %}
						{% if user.is_staff %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'admin_panel' %}">Admin Panel</a>
						</li>
						{% endif %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'about' %}">About Us</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'contact' %}" >Contact Us</a>
						</li>
					</ul>
				</div>
				<div class="col-md-6 text-right">
					<a href="{% url 'cart' %}" class="btn btn-info" style="background-color: #7aa66f; border-color: #7aa66f;"><i class="fa fa-shopping-cart"></i> Shopping Cart</a>
				</div>
			</div>
		</div>
	</div>
	<div>
  		{% block content %}
  		{% endblock content %}
	</div>
  	<!--Footer-->
  	<footer style="background-color: #455047; color:white;  bottom: 0; left: 0; right: 0;" class="py-3">
		<div class="container text-center">
			<p>&copy; 2023 Nut Store. All rights reserved.</p>
		</div>
  	</footer>

	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
	integrity="sha384-PsEuO5d3KJwH8lOt5W5zTjfNAWbO6b1m9MllLZn/9yFJY7g7dCBxL+7ZqOJz9oqJ"
	crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js"
	integrity="sha384-1fX4p6sM2Xwec7fZjCtLsJ2kP5qk2q1F92sK9erWVwk+N8Q5c6qZI3WgXyY/0e2K"
	crossorigin="anonymous"></script>
	<script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
	
	
	<style>
	.nav-link{
		color: #f9f0de;
	}
	
	.nav-link:hover{
		color:rgb(174, 174, 162);
		border-bottom-color: beige;
	}
	</style>
</body>
</html> 

templates/cart.html
{% extends 'base.html' %}

{% block content %}
  <div class="row justify-content-center" style="margin-top: 2rem; margin-bottom: 2rem;">
    <div class="col-md-8">
      <h1 class="text-left mb-5">Shopping Cart</h1>
      {% if cart_items %}
        <div class="row">
          {% for item in cart_items %}
            <div class="col-md-12 mb-4">
              <div class="card border-0 shadow-sm">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-4">
                      {% if item.product.image %}
                        <img src="{{ item.product.image }}" class="card-img-top" alt="{{ item.product.name }}">
                      {% else %}
                        <div class="text-center py-5">
                          <h4 class="m-0">{{ item.product.name }}</h4>
                        </div>
                      {% endif %}
                    </div>
                    <div class="col-md-8">
                      <h4 class="card-title">{{ item.product.name }}</h4>
                      <p class="card-text">{{ item.product.description }}</p>
                      <form action="{% url 'update_cart' item.id %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                          <input type="number" class="form-control" name="weight" value="{{ item.weight }}" step="0.1" min="0">
                          <div class="input-group-append">
                            <span class="input-group-text">Kg</span>
                          </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                          <p class="card-text font-weight-bold">{{ item.product.price }} $</p>
                          <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                      </form>
                      <hr>
                      <div class="d-flex justify-content-between align-items-center">
                        <p class="card-text font-weight-bold">Total Cost:</p>
                        <p class="card-text font-weight-bold">{{ total_cost }} $</p>
                      </div>
                      <form action="{% url 'remove_from_cart' item.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-icon">
                          <i class="fas fa-trash-alt"></i>
                        </button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          <div class="col-md-12 mb-4">
            <div class="card border-0 shadow-sm">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                  <h4 class="card-title font-weight-bold">Total Cost:</h4>
                  <h4 class="card-title font-weight-bold">{{ total_cost }} $</h4>
                </div>
                <form action="{% url 'purchase_confirmation' %}" method="post" onsubmit="return confirm('Are you sure about your purchase?')">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary btn-block">Purchase</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      {% else %}
        <p class="text-center">Your cart is empty.</p>
      {% endif %}
    </div>
  </div>

  <style>
    .card {
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .card-img-top {
      border-top-left-radius: 10px;
      border-bottom-left-radius: 10px;
      height: 200px;
      object-fit: cover;
    }

    .btn-link {
      border: none;
      text-decoration: underline;
      color: #007bff;
    }

    .btn-primary {
      border-radius: 20px;
      padding: 10px 20px;
      color: white;
      background-color: #7aa66f;
      border-color: #7aa66f;
    }

    .btn-primary:hover {
      background-color: #586e52;
      border-color: #586e52;
    }

    
    body {
      /* fallback for old browsers */
        background: #F2F0EB;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, #F2F0EB, rgb(167, 175, 151));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, #F2F0EB, rgb(239, 234, 213))
    }
  </style>
{% endblock %}

templates/categoryproducts.html
{% extends 'base.html' %}


{% block content %}
  <h1 class="text-center mb-5">{{ category|title }}</h1>
  <div class="row justify-content-center" style="margin-top: 2rem; margin-bottom: 2rem;">
    {% for product in products %}
      <div class="col-md-4 mb-4">
        <div class="card h-100 border-0 shadow-sm" style=" border-radius: 1rem; border-color: rgb(230, 230, 230);">
          {% if product.image %}
            <img src="{{ product.image }}" class="card-img-top" alt="{{ product.name }}">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <p class="card-text font-weight-bold">{{ product.price }} $</p>
            <form action="{% url 'add_to_cart' product.id %}" method="get">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-block btn-rounded btn-hover">
                Add to Cart
              </button>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>


{% block extra_css %}
  <style>
    /* .card {
      margin: 1.5rem;
      border-radius: 1rem;
      border-color: rgb(230, 230, 230);
    }

    .row {
      margin-top: 2rem;
      margin-bottom: 2rem;
    } */
    .btn-hover {
      color: white;
      background-color: #7aa66f;
      border-color: #7aa66f;
      border-radius: 5rem;
    }

    .btn-hover:hover {
      background-color: #586e52;
      border-color: #586e52;
    }

  </style>
{% endblock %}
{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <h1 class="text-center mb-5">Contact Us</h1>
        <div class="row justify-content-center">
          <div class="col-md-6 mb-4">
            <div class="card" style="border-radius: 1.3rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);">
              <div class="card-body">
                <h2 class="card-title mb-4" style="color: rgb(199, 80, 32);"><strong>The Nut Store</strong></h2>
                <p class="card-text">Our family-owned business has been providing high-quality nuts and snacks to our customers since 1970. We are committed to quality and freshness, and our customers have come to trust us as a reliable source for their favorite snacks.</p>
                <p class="card-text"><strong>Telephone:</strong> +98 - 21 8835</p>
                <p class="card-text"><strong>Email:</strong> info@nutstore.com</p>
              </div>
            </div>
          </div>
        </div>
          <div class="col--lg-12">
            <div class="card" style="border-radius: 1.3rem; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);">
              <div class="card-body">
                <h2 class="card-title mb-4" style="color: rgb(70, 121, 57);"><b>Store Locations</b></h2>
                <div class="row">
                  <div class="col-md-4">
                    <div class="card" style="border-radius: 1.3rem;">
                      <div class="card-body">
                        <h3 class="card-title"><b>Tehran</b></h3>
                        <p class="card-text">Tehran Grand Bazaar</p>
                        <p class="card-text">Grand Baazar, Hashemi Dalan</p>
                        <p class="card-text">Monday - Friday: 9am - 10pm</p>
                        <p class="card-text">Saturday: 10am - 6pm</p>
                        <p class="card-text">Sunday: Closed</p>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="card" style="border-radius: 1.3rem;">
                      <div class="card-body">
                        <h3 class="card-title"><b>Ardabil</b></h3>
                        <p class="card-text">Ardabil Piratmali Bazaar</p>
                        <p class="card-text">Piratmali, No.56</p>
                        <p class="card-text">Monday - Friday: 10am - 7pm</p>
                        <p class="card-text">Saturday: 9am - 5pm</p>
                        <p class="card-text">Sunday: Closed</p>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="card" style="border-radius: 1.3rem;">
                      <div class="card-body">
                        <h3 class="card-title"><b>Isfahan</b></h3>
                        <p class="card-text">Isfahan Main Baazar</p>
                        <p class="card-text">Grand Baazar, No.456</p>
                        <p class="card-text">Monday- Friday: 10am - 8pm</p>
                        <p class="card-text">Saturday: 9am - 5pm</p>
                        <p class="card-text">Sunday: Closed</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5" style="margin-top: 4rem; margin-bottom: 5rem;">
  <div class="row">
    <div class="col-md-4">
      <div class="card mb-4 border-rounded">
        <div class="card-header header-primary">
          <h3 class="card-title mb-0">Personal Information</h3>
        </div>
        <div class="card-body">
          <p><strong>Name:</strong> {{ user.name }}</p>
          <p><strong>Last Name:</strong> {{ user.family_name }}</p>
          <p><strong>Username:</strong> {{ user.username }}</p>
          <p><strong>City:</strong> {{ user.city }}</p>
          <p><strong>Phone Number:</strong> {{ user.phone_number }}</p>
          <p><strong>Email:</strong> {{ user.email }}</p>
          <p><strong>Address:</strong> {{ user.address }}</p>
          {% if user.is_buyer %}
              <p><strong>Customer type:</strong> Ordinary Customer</p>
          {% elif user.is_seller %}
              <p><strong>Customer type:</strong> WholeSale Customer</p>
          {% endif %}
          <p><a href="{% url 'change_password' %}" style="color: #7aa66f;">Change your password!</a></p>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="card mb-4 border-rounded">
        <div class="card-header header-secondary">
          <h3 class="card-title mb-0">Order History</h3>
        </div>
        <div class="card-body">
          {% if orders %}
            <ul class="list-group list-group-flush">
              {% for order in orders %}
                <li class="list-group-item">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Order ID: {{ order.id }}</h5>
                    <small>{{ order.created_at|date:"F d, Y" }}</small>
                  </div>
                  <p class="mb-1">Order Items:
                    <ul>
                    {% for item in order.items.all %}
                        <li>
                            {{ item.product.name }},
                            Weight: {{ item.weight }} Kg
                        </li>
                    {% endfor %}
                    </ul></p>
                  <p class="mb-1">Order Total Cost: {{ order.total_cost }}</p>
                  <p class="mb-0">Status: {{ order.get_status_display }}</p>
                </li>
              {% endfor %}
            </ul>
          {% else %}
            <p>No orders found.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .header-primary {
    background-color: #719967;
    color: #fff;
    border-color: #7aa66f;
  }
  
  .header-secondary {
    background-color: #719967;
    color: #fff;
    border-color: #7aa66f;
  }
  
  .border-rounded {
    border-radius: 10px;
  }
</style>
{% endblock %}

templates/purchase_confirmation.html
{% extends 'base.html' %}

{% block content %}
  <div class="container" style="margin: 10rem;">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card" style="border-radius: 1rem;">
          <div class="card-header text-center" style="background-color: #7aa66f">
            <h1 class="card-title">Thank you for your purchase!</h1>
          </div>
          <div class="card-body text-center">
            <p class="lead">Your order has been confirmed. Here are the details:</p>
            <ul class="list-group mb-3">
              {% for item in order.cartitem_set.all %}
                <li class="list-group-item">{{ item.product.name }} - {{ item.weight }}{% if not request.user.is_seller %}g{% else %}kg{% endif %} - {{ item.product.price }} * {{ item.weight }}</li>
              {% endfor %}
            </ul>
            <p class="lead">Total cost: {{ order.total_cost }}</p>
            <p class="lead">Order ID: {{ order.id }}</p>
            <div class="d-grid gap-2">
              <p><a href="{% url 'profile' %}" class="btn btn-primary">View Profile</a></p>
              <p><a href="{% url 'home' %}" class="btn btn-secondary">Return to Homepage</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% block extra_css %}
  <style>

  .btn-primary {
    
    padding: 10px 20px;
    color: white;
    background-color: #7aa66f;
    border-color: #7aa66f;
  }

  .btn-primary:hover {
    background-color: #586e52;
    border-color: #586e52;
  }


</style>
{% endblock %}
{% endblock %}